import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import test from "node:test";
import { resolveRange } from "./range.mjs";

const a = "a".repeat(40);
const b = "b".repeat(40);

// Messages go through the real commitlint with the repository config; these
// tests cover our configuration and wrapper, not commitlint's own rules.
function lint(message) {
  return spawnSync(
    "pnpm",
    ["exec", "commitlint", "--config", "commitlint.config.mjs"],
    { input: message, encoding: "utf8" },
  );
}

test("accepts conventional subjects, with and without a scope", () => {
  assert.equal(lint("fix: handle empty input\n").status, 0);
  assert.equal(lint("refactor(seo): move metadata helpers\n").status, 0);
});

test("accepts breaking-change syntax", () => {
  assert.equal(lint("feat(api)!: drop the old route\n").status, 0);
  assert.equal(
    lint("feat: new route\n\nBREAKING CHANGE: the old route is gone\n").status,
    0,
  );
});

test("accepts the content type used for posts", () => {
  assert.equal(lint("content: add sweep learning post\n").status, 0);
});

test("rejects a subject that is not conventional, and says why", () => {
  const result = lint("Updated some things\n");
  assert.notEqual(result.status, 0);
  assert.match(result.stdout, /subject may not be empty|type may not be empty/);
  assert.notEqual(lint("wip: half done\n").status, 0);
});

test("ignores merge and revert commits generated by git and GitHub", () => {
  assert.equal(lint("Merge pull request #15 from owner/branch\n").status, 0);
  assert.equal(lint("Merge branch 'main' into feature\n").status, 0);
});

test("a pull request checks exactly base..head", () => {
  assert.deepEqual(resolveRange({ event: "pull_request", base: a, head: b }), {
    kind: "range",
    from: a,
    to: b,
  });
  assert.throws(() => resolveRange({ event: "pull_request", base: a }));
});

test("a push checks before..after unless there is no previous commit", () => {
  assert.deepEqual(resolveRange({ event: "push", before: a, after: b }), {
    kind: "range",
    from: a,
    to: b,
  });
  for (const before of ["0".repeat(40), "", undefined]) {
    assert.equal(
      resolveRange({ event: "push", before, after: b }).kind,
      "skip",
    );
  }
});

test("manual runs and unknown events invent no range", () => {
  assert.equal(resolveRange({ event: "workflow_dispatch" }).kind, "skip");
  assert.equal(resolveRange({ event: "schedule" }).kind, "skip");
});

test("local use defaults to origin/main..HEAD and honours --from/--to", () => {
  assert.deepEqual(resolveRange({}), {
    kind: "range",
    from: "origin/main",
    to: "HEAD",
  });
  assert.deepEqual(resolveRange({ from: "v1", to: "v2" }), {
    kind: "range",
    from: "v1",
    to: "v2",
  });
});

test("an empty range is a pass, not an error", () => {
  const result = spawnSync(
    "node",
    ["commits/check.mjs", "--from", "HEAD", "--to", "HEAD"],
    { encoding: "utf8" },
  );
  assert.equal(result.status, 0);
  assert.match(result.stdout, /No commits in/);
});

test("an unknown ref fails with a hint instead of passing", () => {
  const result = spawnSync(
    "node",
    ["commits/check.mjs", "--from", "no-such-ref"],
    {
      encoding: "utf8",
    },
  );
  assert.equal(result.status, 2);
  assert.match(result.stderr, /Unknown commit/);
});

test("CI passes event data to the check only through env", async () => {
  const { readFile } = await import("node:fs/promises");
  const ci = await readFile(
    new URL("../.github/workflows/ci.yml", import.meta.url),
    "utf8",
  );
  const step = ci.slice(ci.indexOf("- name: Commit messages"));
  const block = step.slice(0, step.indexOf("\n\n"));
  assert.match(block, /run: node commits\/check\.mjs\n/);
  for (const name of ["EVENT", "BASE", "HEAD", "BEFORE", "AFTER"]) {
    assert.match(block, new RegExp(`COMMITS_${name}: \\$\\{\\{`));
  }
  assert.ok(!/run:[^\n]*\$\{\{/.test(block));
  assert.match(ci, /fetch-depth: 0/);
});
